using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace THANHTOANTROIGIO.Controllers
{
    [Route("import")]
    public class ImportController : Controller
    {
       
        public class selectSheet
        {
            public int id { get; set; }
            public int value { get; set; }
            public string text { get; set; }
            public selectSheet(int id, int value, string text)
            {
                this.id = id;
                this.value = value;
                this.text = text;
            }
        }
        public IActionResult Index()
        {
            return View();
        }
        [Route("list-sheet")]
        [HttpPost]
        public JsonResult getTenSheet(MultipartFormDataContent formTTTN)
        {
            var rq = HttpContext.Request.Form;
            var file = rq.Files.Count() > 0 ? rq.Files[0] : null;
            var maNKHK = rq["maNKHK"].ToString();
            if (file != null)
            {
                var filePath = Path.GetTempFileName();
                ExcelPackage.LicenseContext = LicenseContext.Commercial;

                using (var stream = System.IO.File.Create(filePath))
                {
                    // The formFile is the method parameter which type is IFormFile
                    // Saves the files to the local file system using a file name generated by the app.
                    file.CopyToAsync(stream);
                }
                using (var package = new ExcelPackage(filePath))
                {
                    ExcelPackage.LicenseContext = LicenseContext.Commercial;
                    var workbook = package.Workbook;
                    var worksheet = workbook.Worksheets;
                    List<selectSheet> listSheet = new List<selectSheet>();
                    foreach (var ws in worksheet)
                    {
                        listSheet.Add(new selectSheet(ws.Index, ws.Index, ws.Name));
                    }
                    return Json(new { success = true, data = listSheet });
                }
            }
            else
            {
                return Json(new { success = false, data = "Lỗi" });
            }
        }
    }
}
